server:
  port: 9004
spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.18.77:3306/tensquare_article?characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql